# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 16e0e72659671988852be568337c9f0713560f2313cc8a5bac17232d38da6aea0dc27c1b2d0b85a0f75dd93c47adf6d99758ca7f4deb6cb419b3fc69d80fadd1

test:
  secret_key_base: 0f4c6fca927ffc4983104e5d84e9fa826769696a70294851c7a13a46c6c18cfbf01df27e70e6806196955539cbb8dacc529c336ff95b390385d6e96565e1b940

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
